### ISSUE TITLE
about "top_img"

### ISSUE THREAD

**Issue by YuanClouds** [Molunerfinn/hexo-theme-melody#147]
tag ：v1.5.5
issue:
     i'm setting "top_img:https://XXX.jpg" in _config.yml.but i don't see that my blog has any change?

```
# Site
title: i am title
subtitle: coding
description: 
keywords:
author: hi
language:
timezone:
top_img: https://XXX.jpg
social:
  github: https://github.com/Molunerfinn
  weibo: http://weibo.com/mybluedreams
  rss: https://Molunerfinn/atom.xml
```
