### ISSUE TITLE
Can not display discord social icon

### ISSUE THREAD

**Issue by j0ck1e** [Molunerfinn/hexo-theme-melody#150]
**Melody Version: v1.5.6**
**Platform: Linux**
**Browser: FireFox**

## Expected behavior 
add discord social icon for my blog
## Actual behavior 
![](https://files.catbox.moe/318nqt.png)
![](https://files.catbox.moe/m2rf73.png)

## Steps to reproduce the behavior 
- get icon_name
<https://fontawesome.com/icons/discord?style=brands>
- add configure to _config.yml
```yaml
social:
  #icon_name: url
  discord: https://discordapp.com/users/439441945337790475
```
- `hexo g`

**Comment by j0ck1e** [comment]
### _config.yml
```yaml
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
```
