### ISSUE TITLE
toc expands all at once  

### ISSUE THREAD

**Issue by zhangxin6** [Molunerfinn/hexo-theme-melody#169]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
2019.01.13  branch:dev（最新版）

**Platform:**
Windows

**Browser:**
Chrome
## Expected behavior 
* Directory expands with content（目录随着内容展开）
* Click on the left side of the directory to jump to the blog related page（在左边目录中点击跳转到博客相关页面）
## Actual behavior 
* The catalogue is fully expanded at once(目录一下全展开)
* The directory on the left clicks no response（左边目录点击无响应）

![错误截图](https://zhangxin-1258487717.cos.ap-beijing.myqcloud.com/toc%E5%B1%95%E5%BC%80%E4%B8%8D%E6%AD%A3%E7%A1%AE.png)
我看了作者的网站，似乎并不存在这个问题。初步看是scroll.js和设计不一致，但没找到问题所在。
## Steps to reproduce the behavior 
markdown文件如下：
```
---
title: HDLC 发送的FPGA设计
date: 2019-01-11 18:18:12
tags: iverilog
categories: fpga 
---
## 摘要
关于HDLC 发送的设计思路和源码使用方法。
## HDLC协议格式
| 帧头标志 | 地址   | 控制   | 信息    | 校验    | 帧尾标志 |
| :-: | :-: | :-: | :-: | :-: | :-: |
| 4个7E    | 自定义 | 自定义 | 自定义 | 16位CRC | 4个7E    |
注意：[HDLC](https://baike.baidu.com/item/HDLC%E5%8D%8F%E8%AE%AE) 帧头和帧尾只规定至少1个7E，实际用几个属于内部协议。
## 模块架构
## Feature Request
```

---
[访问此博客链接，可重现问题](https://zhangxin6.github.io/2019/01/11/hdlctra%EF%BC%88HDLC%E5%8F%91%E9%80%81%EF%BC%89/)

**Comment by Molunerfinn** [comment]
提供一份完整的markdown文件，我下周找个时间解决一下这个问题

**Comment by Molunerfinn** [comment]
前几天改过一次这个侧边栏， @kawa-yoiko 有空的话也可以关注一下。

**Comment by Molunerfinn** [comment]
就目前而言你可以先用`master`分支的`scroll.js`来渲染页面。`dev`分支不太稳定不适合直接上线

**Comment by zhangxin6** [comment]
[完整的markdown文件](https://raw.githubusercontent.com/zhangxin6/zhangxin_blog/master/source/_posts/hdlctra%EF%BC%88HDLC%E5%8F%91%E9%80%81%EF%BC%89.md)
非常感谢！

**Comment by zhangxin6** [comment]
我把scroll.js改成了master分支的，这个问题依然存在。我猜可能是markdown哪里有问题。

**Comment by kawa-yoiko** [comment]
应该是因为各级标题（h1~h6）的 id 为空，所以无法判断位置。似乎是 markdown 渲染器造成的。

@zhangxin6 有换过 markdown 渲染器，或者改过它的选项嘛…… 自带的 marked，以及 markdown-it 插件默认应该都会为 h1~h6 加上 id 的…

**Comment by upupming** [comment]
@zhangxin6 
markdown 文件和 `melody` 都没有问题，我这边测试过了。
应该是你的配置出错了，请自行阅读一下 https://molunerfinn.com/hexo-theme-melody-doc/ 如何正确配置 melody。

**Comment by kawa-yoiko** [comment]
可能我对 hexo 还是不太了解，没有找到很简单的复现方法（看到的几个 markdown 渲染器都会给标题加上 anchor，似乎也没有关闭的选项……）

目前的复现方法是在 hexo-renderer-markdown-it-plus 渲染器的默认配置下将 `node_modules/hexo-renderer-markdown-it-plus/lib/renderer.js` 的 [这几行](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus/blob/72bd987ff5288f9743fb87e255ebc6d55a6a43d0/lib/renderer.js#L120-L123) 注释掉，改成 `return md;`。这样 anchor 被禁用，就会出现全部展开的问题。

但是渲染器默认并不禁用 anchor，所以我觉得是修改了 markdown 渲染器配置导致的错误。

想过加上一个 hack 处理这种情况，但没有 anchor 引起的问题不止这一个，处理起来很混乱…… 所以还是推荐重新检查一下配置啦，实在不行把 `_config.yml` 和 `package.json` 贴上来也可以……

（markdown 渲染器需要开启 anchor 这件事在文档里提一下比较好？

**Comment by zhangxin6** [comment]
package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "markdown-it-emoji": "^1.4.0"
  }
}
```
根目录下的_config.yml
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title:
subtitle:
description:
author: Zhang Xin
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://zhangxin6.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-melody

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:zhangxin6/zhangxin6.github.io.git
  branch: master

markdown:
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
    - markdown-it-abbr
    - markdown-it-emoji
```

**Comment by zhangxin6** [comment]
我认为这个问题演变成了一个功能需求，即：如何在主题中加入emoji表情。我认为这种需求，应该是广泛的，并且值得在文档里提及的。

**Comment by Molunerfinn** [comment]
@zhangxin6 如果你只是想要emoji，那么你简单安装一下`hexo-renderer-markdown-it-plus`就行了。
![image](https://user-images.githubusercontent.com/12621342/51163170-ca237c00-18d3-11e9-92b5-16e58ab969f6.png)
地址：https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus

如果觉得需要我可以在文档里提一句。

**Comment by kawa-yoiko** [comment]
我成功复现了 XD… 在 `_config.yml` 的结尾加上这个就能恢复正常（[doc](https://github.com/hexojs/hexo-renderer-markdown-it/wiki/Advanced-Configuration)）

```yml
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: false
```

不过确实 markdown-it 不是主题默认支持的… 还是按 @Molunerfinn 说的改用 markdown-it-plus 好啦
