### ISSUE TITLE
something wrong to run hexo-theme-melody

### ISSUE THREAD

**Issue by kimmking** [Molunerfinn/hexo-theme-melody#182]
step 1: install dependencies
```
$ npm install hexo-renderer-jade hexo-renderer-stylus --save
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
+ hexo-renderer-stylus@0.3.3
+ hexo-renderer-jade@0.4.1
updated 2 packages and audited 4906 packages in 5.221s
found 6 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

Step 2: then   run "hexo generate" will failed:
```
ERROR Process failed: layout/archive.pug
Error: /Users/kimmking/themes/melody/layout/includes/footer.pug:5:18
    3|   - var nowYear = now.getFullYear()
    4|   if theme.since && theme.since != nowYear
  > 5|     .copyright!= `&copy;${theme.since} - ${nowYear} By ${config.author}`
------------------------^
    6|   else
    7|     .copyright!= `&copy;${nowYear} By ${config.author}`
    8|   .framework-info

Syntax Error: Unexpected character '`'
    at makeError (/Users/kimmking/node_modules/pug-error/index.js:32:13)

```
other info:
```
$ hexo -v

hexo: 3.8.0
hexo-cli: 1.1.0
os: Darwin 18.2.0 darwin x64
http_parser: 2.8.0
node: 10.8.0
v8: 6.7.288.49-node.19
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

How can I do something to fix it? thx.

**Comment by Molunerfinn** [comment]
Show me your hexo-site's `package.json`, it's a weird mistake

**Comment by kimmking** [comment]
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
keywords:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: melody

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

```
