### ISSUE TITLE
No search bar in algolia search

### ISSUE THREAD

**Issue by charon-cheung** [Molunerfinn/hexo-theme-melody#206]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: 1.6**

**Platform: Windows**

**Browser: Chrome FireFox**

## Expected behavior 
![image](https://user-images.githubusercontent.com/51428916/59199265-20b58d80-8bc8-11e9-8cf6-7c5444cef9ec.png)

## Actual behavior 
![image](https://user-images.githubusercontent.com/51428916/59199264-1f846080-8bc8-11e9-8cf6-da823c2c951f.png)

## Steps to reproduce the behavior 
I set following in both `melogy.yml` and `_config.yml`( in the root dir)
```
algolia_search:
  enable: true
  hits:
    per_page: 10

algolia:
  applicationID: 'RI90VLL69D'
  apiKey: '20c535e9a1424a7913210eb747d6e67b'
  adminApiKey: '8bc04674458450e477330a7314c0432c'
  indexName: 'HexoBlog'
  chunkSize: 5000
```
![image](https://user-images.githubusercontent.com/51428916/59199325-42af1000-8bc8-11e9-9e1e-991d27de3a35.png)

when executing `hexo algolia`, I got following errors:
![image](https://user-images.githubusercontent.com/51428916/59199582-dda7ea00-8bc8-11e9-9364-9c7559c25d94.png)

But I still can see search result in the browser of algolia
![image](https://user-images.githubusercontent.com/51428916/59199513-b6e9b380-8bc8-11e9-8f7d-bfa92454cdab.png)
So the problem is only the search bar

## Feature Request

---
