### ISSUE TITLE
配置好了Valine，并把Disqus关了，但是博客评论区域现在什么也没有

### ISSUE THREAD

**Issue by supersu097** [Molunerfinn/hexo-theme-melody#237]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Steps to reproduce the behavior 
请访问http://sharpgan.com/2019/10/23/python-images-compressing/复现
## Feature Request

---

**Comment by supersu097** [comment]
我在public文件下面grep valine什么都没有，grep disqus倒是返回一大堆，说明hexo g的时候valine相关的代码没有生成，我的valine配置如下：
```
valine:
  enable: true # if you want use valine,please set this value is ture
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: true # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: retro # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: 请留下你的评论吧～ # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header inf
```
