### ISSUE TITLE
upgrade gittalk 1.5.1

### ISSUE THREAD

**Issue by akinix** [Molunerfinn/hexo-theme-melody#260]
# GitHub app API query parameter deprecation
GitHub is going to be deprecating sending the client ID and client secret as query parameters. Gitalk will need to be updated to use basic authentication. For more information see: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters

[the issue detail](https://github.com/gitalk/gitalk/issues/343) 

# how to upgrade gittalk?
edit *layout\includes\comments\gitalk.pug*
```
if theme.gitalk && theme.gitalk.enable
  - let lang = config.language === 'zh-Hans' ? 'zh-CN' : config.language
  #gitalk-container
  script.
    var gitalk = new Gitalk({
      clientID: '!{theme.gitalk.client_id}',
      clientSecret: '!{theme.gitalk.client_secret}',
      accessToken: '!{theme.gitalk.access_Token}',
      repo: '!{theme.gitalk.repo}',
      owner: '!{theme.gitalk.owner}',
      admin: '!{theme.gitalk.admin}',
      id: md5(decodeURI(location.pathname)),
      language: '!{lang}'
    })
    gitalk.render('gitalk-container')
```

# new config for users
- Goto [accessToken](https://github.com/settings/tokens) to generate a public read-only token
- Use the new gitalk.min.js to replace the old one
- Config your token in your template

edit `melody.yml`
```yml
gitalk:
  enable: true
  client_id: xxx
  client_secret: xxx
  access_Token: xxx // IMPORTANT !!!
  repo: xxx
  owner: xxx
  admin: xxx
  language: zh-CN
  js: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js // version must be 1.5.1
```
