### ISSUE TITLE
使用CI部署报错"WARN  No layout: index.html"等且渲染的页面空白

### ISSUE THREAD

**Issue by AyagawaSeirin** [Molunerfinn/hexo-theme-melody#262]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**1.7.0

**Platform:**Windows

**Browser:**Chrome

## Expected behavior 
使用CI部署构建静态文件，完全参考您的文章<https://molunerfinn.com/hexo-travisci-https>进行部署的。
## Actual behavior 
构建时报错，且构建后相关文件空白
报错信息(部分截取)：
```
$ hexo generate
INFO  Start processing
INFO  Files loaded in 68 ms
WARN  No layout: 2020/02/13/hello-world/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/2020/index.html
WARN  No layout: archives/2020/02/index.html
WARN  No layout: index.html
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2020/02/index.html
INFO  Generated: archives/2020/index.html
INFO  Generated: 2020/02/13/hello-world/index.html
INFO  5 files generated in 12 ms
The command "hexo generate" exited with 0.
```

## Feature Request

---

**Comment by AyagawaSeirin** [comment]
因为我没有装algolia，所以把script的内容改成了
```
script:
  # - hexo algolia # 我装了algolia的搜索工具。这一步正常可以是 hexo g
  - hexo clean
  - hexo generate
```
其他也有小更改，比如以master分支作为源码分支，gh-pages分支作为静态文件分支，都对应的改过来了。

**Comment by AyagawaSeirin** [comment]
.travis.yml内容：
```
language: node_js # 声明环境为node
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules # 缓存node_modules文件夹

# S: Build Lifecycle
install:
  - npm install # 下载依赖

script:
  # - hexo algolia # 我装了algolia的搜索工具。这一步正常可以是 hexo g
  - hexo clean
  - hexo generate


after_script: # 推送到github的部分
  - cd ./public
  - git init
  - git config user.name "ayagawaseirin"
  - git config user.email "461514286@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages # 通过之前存在Travis-CI里的token以及github仓库的地址推送到相应的master分支
# E: Build LifeCycle

branches:
  only:
    - master # 只对master分支构建

env: # 环境变量
 global:
   - GH_REF: github.com/AyagawaSeirin/Blog.git # 我的仓库地址
```
