### ISSUE TITLE
无法正常使用local-serach

### ISSUE THREAD

**Issue by PowderHan** [Molunerfinn/hexo-theme-melody#270]
您好，我按照您的说明正常添加了local-search插件，配置如下：

⇒  npm install hexo-generator-search
+ hexo-generator-search@2.4.0
updated 1 package in 3.802s

```
local_search:
  enable: true # or false
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result

----
source/_data/melody.yml
```

```
search:
  path: search.xml
  field: post
  content: true

----
_config.yml
```

但是搜索框不管输入什么都没有反应，这是为什么呢？
search.xml好像是正常生成了。

我的网址是http://106.15.75.209:81/

非常感谢
