### ISSUE TITLE
文章页中使用本地搜索，会被当成相对链接访问

### ISSUE THREAD

**Issue by test-lin** [Molunerfinn/hexo-theme-melody#327]
## Melody Information

**yarn Version:** 1.22.4
**hexo-cli Version:** 4.2.0
**Melody Version:**  1.9.0
**hexo-generator-search Version:** 2.4.2

**Platform:** Windows 7

**Browser:** edge

**_config.melody.yml**

```yml
local_search:
  enable: true
  labels:
    input_placeholder: '文章搜索'
    hits_empty: '找不到搜索结果: ${query}'
```

## Expected behavior 

跳转到搜索结果页

http://localhost:4000/2019/04/ssl-encrypt/

## Actual behavior 

实际跳转到 http://localhost:4000/2019/04/algorithm-roman-to-integer/2019/04/ssl-encrypt/

## Steps to reproduce the behavior 

1. 进入文章详情页
2. 点击头部搜索进行搜索
3. 点击搜索结果

## Other

从访问错误页返回，重新打开搜索，搜索关键词还在，无搜索结果，需要删除一部分才能触发
