### ISSUE TITLE
建议Footer加入一个区域写备案号

### ISSUE THREAD

**Issue by sunhailin-Leo** [Molunerfinn/hexo-theme-melody#35]
建议Footer加入一个区域写备案号:blush: :blush:

**Comment by sunhailin-Leo** [comment]
补上我自己用melody做的页面~

[http://www.leoyuki.xyz](http://www.leoyuki.xyz)

**Comment by Molunerfinn** [comment]
Footer的ICP备案号区域一直都有。不过我好像没加到说明文档里。回头我加到文档里去。

开启方法，找到主题的配置文件：

```
ICP:
  enable: true
  url: # 你的ICP备案的url
  text: # 你的ICP备案文本
```

你的页面之后我会放到主页上。如果喜欢这个主题欢迎点个star，谢谢: )
