### ISSUE TITLE
AlgoliaSearchError

### ISSUE THREAD

**Issue by zouyaoji** [Molunerfinn/hexo-theme-melody#39]
您好，不好意思，打扰请教一个问题。
我更新了一篇文章，推送的时候编译不通过，提示AlgoliaSearchError，我在Algolia日志查到这个。
{
  "message": "Record at the position 0 objectID=cje9eh9ey0004bz5myy2x96is is too big size=13816 bytes. Contact us if you need an extended quota",
  "position": 0,
  "objectID": "cje9eh9ey0004bz5myy2x96is",
  "status": 400
}

不知道这个是具体说我内容、还是标题什么的太长了？

**Comment by zouyaoji** [comment]
我去Algolia查了查，说是免费的账户，上传的只能上传 10KB，但是我文章内容并不长，难道要分成多篇写？ 请问博主您是怎么避免这种情况的？

**Comment by Molunerfinn** [comment]
这个不是hexo-theme-melody的问题...不过我一开始用algolia的时候是遇到过的。解决办法如下。
首先我用的是：`hexo-algoliasearch`
然后我的配置项是：
```yaml
algolia: 
  appId: xxx
  apiKey: xxx
  adminApiKey: xxx
  indexName: xxx
  chunkSize: 5000
  fields:
    - title
    - tags
    - categories
    - excerpt:strip
    - content:strip
    - slug
    - permalink
    - path
```
需要改的就是那个chunkSize和fileds来指定你要存到algolia里的东西。我并不是存完整的内容，而是`content:strip`做了压缩处理。这点弄完应该就可以了。如果还不行。。请去hexo-algoliasearch的github issues里提，这个并不属于melody的问题。
