### ISSUE TITLE
Sidebar links display problem & gitalk language support

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#56]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.1

**Platform:** Ubuntu 17.10

**Browser:** Chrome

## Expected behavior  && Actual behavior 
I added several links to my `melody.yml`:
```yml
# Sidebar Settings
# ---------------
links_title: 友情链接
links:
    #Name: url
    提问的智慧: https://gist.github.com/zer4tul/95ffaa741c836dc6ab3b
    中文维基百科: https://zh.wikipedia.org/
    ZBQTesla的博客: https://zbqtesla.github.io
```

But they didn't display as expected:
![screenshot from 2018-04-05 12-57-57](https://user-images.githubusercontent.com/24741764/38347988-97067558-38d1-11e8-80df-d58f4f70a2ec.png)

I found the second link cannot be diaplay well, but I cannot figure out why this happened.

I would prefer displaying the links like below(I added `<br>` to the `layout/includes/sidebar.pug` file):
![screenshot from 2018-04-05 12-58-43](https://user-images.githubusercontent.com/24741764/38348045-0ad9f392-38d2-11e8-98c3-7e24687aac12.png)
What do you think?

## Feature Request

I found I cannot change the language of **gitalk** in the `melody.yml`. 

According to [gitalk doc](https://github.com/gitalk/gitalk#options), I think you can change its `language` option to `zh-CN` if the `language: zh-Hans` is set in `_config.yml`.
<hr>

Another thing, I found change the color of this theme is really convenient, I can just change them in `var.styl`. However the name of color variables such as `$light-blue` is confusing when I want to change its value. If you use `$main-color`, it will be much understandable. Maybe you can write documentation for color configuration?
