### ISSUE TITLE
Hexo g 编译报错  layout.pug:11

### ISSUE THREAD

**Issue by CmcnPro** [Molunerfinn/hexo-theme-melody#58]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:1.5.2

**Platform:Windows

**Browser:Chrome

## Expected behavior 
使用Hexo g 进行编译渲染
## Actual behavior 
报错

```
ERROR D:\githubio\themes\melody\layout\includes\layout.pug:11
    9|
    10| - var pageDescription = page.description || page.title || config.description || ''
  > 11| - var pageKeywords = (config.keywords || []).join(',')
    12| - if (page.tags && page.tags.data) pageKeywords = page.tags.data.map(function(tag) {return tag.name;}).join(',')
    13| - var pageAuthor = config.author + ',' + config.email
    14| - var pageCopyright = config.copyright || config.author

(config.keywords || []).join is not a function
TypeError: D:\githubio\themes\melody\layout\includes\layout.pug:11
    9|
    10| - var pageDescription = page.description || page.title || config.description || ''
  > 11| - var pageKeywords = (config.keywords || []).join(',')
    12| - if (page.tags && page.tags.data) pageKeywords = page.tags.data.map(function(tag) {return tag.name;}).join(',')
    13| - var pageAuthor = config.author + ',' + config.email
    14| - var pageCopyright = config.copyright || config.author

(config.keywords || []).join is not a function
    at eval (eval at wrap (D:\githubio\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:20:44)
    at template (eval at wrap (D:\githubio\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1001:72)
    at Theme._View.View._compiled (D:\githubio\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (D:\githubio\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\githubio\node_modules\hexo\lib\hexo\index.js:390:29
    at tryCatcher (D:\githubio\node_modules\bluebird\js\release\util.js:16:23)
    at D:\githubio\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\githubio\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

自己编辑配置文件还是直接使用主题默认配置文件均此错误

## Feature Request

---

**Comment by Molunerfinn** [comment]
提供一下你的hexo目录的`package.json`以及你hexo站点的`_config.yml`（不是melody的config）

**Comment by CmcnPro** [comment]
### package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.5.0"
  },
  "dependencies": {
    "hexo": "^3.5.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-fs": "^0.2.2",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-search": "^2.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1",
    "hexo-util": "^0.6.3"
  }
}
```

### _config.yml
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: yGin.pro
subtitle: yGin's private plot
description: yGin910
author: yGin
language: zh-CN
timezone: UTC
keywords: yGin910

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://ygin.pro
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: 

# Category & Tag
default_category: uncategorized
category_map: 
tag_map: 

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: melody

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:CmcnPro/cmcnpro.github.io.git
  branch: master

feed:
  type: atom
  path: atom.xml
  limit: 0

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true 
```
